version: '2'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        ports:
            - "5672:5672"

    worker:
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - .:/
        links:
            - rabbit
        depends_on:
            - rabbit